In [1]:
import pandas as pd
import numpy as np

df= pd.read_csv("german.data",sep=" ",header=None)

In [2]:
print("Shape:",df.shape)
print("\nFirst 5 rows :")
display(df.head())

records=len(df)
print(f"Number of records in the data set : {records}")

print(df.columns)

print("\nData Types")
print(df.dtypes)

Shape: (1000, 21)

First 5 rows :

,0,1,2,3,4,5,6,7,8,9,...,11,12,13,14,15,16,17,18,19,20
0,A11,6,A34,A43,1169,A65,A75,4,A93,A101,...,A121,67,A143,A152,2,A173,1,A192,A201,1
1,A12,48,A32,A43,5951,A61,A73,2,A92,A101,...,A121,22,A143,A152,1,A173,1,A191,A201,2
2,A14,12,A34,A46,2096,A61,A74,2,A93,A101,...,A121,49,A143,A152,1,A172,2,A191,A201,1
3,A11,42,A32,A42,7882,A61,A74,2,A93,A103,...,A122,45,A143,A153,1,A173,2,A191,A201,1
4,A11,24,A33,A40,4870,A61,A73,3,A93,A101,...,A124,53,A143,A153,2,A173,2,A191,A201,2

Number of records in the data set : 1000
Int64Index([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
            19, 20],
           dtype='int64')

Data Types
0     object
1      int64
2     object
3     object
4      int64
5     object
6     object
7      int64
8     object
9     object
10     int64
11    object
12     int64
13    object
14    object
15     int64
16    object
17     int64
18    object
19    object
20     int64
dtype: object

In [3]:
df.columns=[f"A{i}" for i in range(1,22)]
print(df.columns)

Index(['A1', 'A2', 'A3', 'A4', 'A5', 'A6', 'A7', 'A8', 'A9', 'A10', 'A11',
       'A12', 'A13', 'A14', 'A15', 'A16', 'A17', 'A18', 'A19', 'A20', 'A21'],
      dtype='object')

In [4]:
print(df["A1"].value_counts())

A14    394
A11    274
A12    269
A13     63
Name: A1, dtype: int64

In [5]:
for i in (df.columns):
    print(df[i].value_counts())

A14    394
A11    274
A12    269
A13     63
Name: A1, dtype: int64
24    184
12    179
18    113
36     83
6      75
15     64
9      49
48     48
30     40
21     30
10     28
60     13
27     13
42     11
11      9
20      8
8       7
4       6
45      5
7       5
39      5
14      4
13      4
33      3
28      3
54      2
16      2
22      2
47      1
5       1
26      1
72      1
40      1
Name: A2, dtype: int64
A32    530
A34    293
A33     88
A31     49
A30     40
Name: A3, dtype: int64
A43     280
A40     234
A42     181
A41     103
A49      97
A46      50
A45      22
A44      12
A410     12
A48       9
Name: A4, dtype: int64
1478    3
1262    3
1258    3
1275    3
1393    3
       ..
1459    1
882     1
3758    1
1136    1
4576    1
Name: A5, Length: 921, dtype: int64
A61    603
A65    183
A62    103
A63     63
A64     48
Name: A6, dtype: int64
A73    339
A75    253
A74    174
A72    172
A71     62
Name: A7, dtype: int64
4    476
2    231
3    157
1    136
Name: A8, dtype: int64
A93    548
A92    310
A94     92
A91     50
Name: A9, dtype: int64
A101    907
A103     52
A102     41
Name: A10, dtype: int64
4    413
2    308
3    149
1    130
Name: A11, dtype: int64
A123    332
A121    282
A122    232
A124    154
Name: A12, dtype: int64
27    51
26    50
23    48
24    44
28    43
25    41
30    40
35    40
36    39
31    38
29    37
32    34
33    33
34    32
37    29
22    27
40    25
38    24
42    22
39    21
46    18
43    17
47    17
44    17
41    17
45    15
20    14
21    14
49    14
50    12
48    12
54    10
57     9
52     9
51     8
55     8
63     8
61     7
53     7
60     6
65     5
58     5
64     5
66     5
74     4
67     3
68     3
56     3
59     3
75     2
19     2
62     2
70     1
Name: A13, dtype: int64
A143    814
A141    139
A142     47
Name: A14, dtype: int64
A152    713
A151    179
A153    108
Name: A15, dtype: int64
1    633
2    333
3     28
4      6
Name: A16, dtype: int64
A173    630
A172    200
A174    148
A171     22
Name: A17, dtype: int64
1    845
2    155
Name: A18, dtype: int64
A191    596
A192    404
Name: A19, dtype: int64
A201    963
A202     37
Name: A20, dtype: int64
1    700
2    300
Name: A21, dtype: int64

In [8]:
df.columns=["cheking_status", "duration","credit_history","purpose","credit_amount","savings","employment","installment_rate","personal_status_sex","other_debtors","residents_since","property","age","other_installment_plans","housing","existing_credits","job","maintainance_dependents","telephone","foreign_worker","credit_risk"]

In [9]:
print(df.columns)

Index(['cheking_status', 'duration', 'credit_history', 'purpose',
       'credit_amount', 'savings', 'employment', 'installment_rate',
       'personal_status_sex', 'other_debtors', 'residents_since', 'property',
       'age', 'other_installment_plans', 'housing', 'existing_credits', 'job',
       'maintainance_dependents', 'telephone', 'foreign_worker',
       'credit_risk'],
      dtype='object')

In [10]:
display(df.head())

,cheking_status,duration,credit_history,purpose,credit_amount,savings,employment,installment_rate,personal_status_sex,other_debtors,...,property,age,other_installment_plans,housing,existing_credits,job,maintainance_dependents,telephone,foreign_worker,credit_risk
0,A11,6,A34,A43,1169,A65,A75,4,A93,A101,...,A121,67,A143,A152,2,A173,1,A192,A201,1
1,A12,48,A32,A43,5951,A61,A73,2,A92,A101,...,A121,22,A143,A152,1,A173,1,A191,A201,2
2,A14,12,A34,A46,2096,A61,A74,2,A93,A101,...,A121,49,A143,A152,1,A172,2,A191,A201,1
3,A11,42,A32,A42,7882,A61,A74,2,A93,A103,...,A122,45,A143,A153,1,A173,2,A191,A201,1
4,A11,24,A33,A40,4870,A61,A73,3,A93,A101,...,A124,53,A143,A153,2,A173,2,A191,A201,2

In [14]:
print(df.info())
print(df.describe())
print(df.isnull().sum())
print(df["credit_risk"].value_counts())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 21 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   cheking_status           1000 non-null   object
 1   duration                 1000 non-null   int64
 2   credit_history           1000 non-null   object
 3   purpose                  1000 non-null   object
 4   credit_amount            1000 non-null   int64
 5   savings                  1000 non-null   object
 6   employment               1000 non-null   object
 7   installment_rate         1000 non-null   int64
 8   personal_status_sex      1000 non-null   object
 9   other_debtors            1000 non-null   object
 10  residents_since          1000 non-null   int64
 11  property                 1000 non-null   object
 12  age                      1000 non-null   int64
 13  other_installment_plans  1000 non-null   object
 14  housing                  1000 non-null   object
 15  existing_credits         1000 non-null   int64
 16  job                      1000 non-null   object
 17  maintainance_dependents  1000 non-null   int64
 18  telephone                1000 non-null   object
 19  foreign_worker           1000 non-null   object
 20  credit_risk              1000 non-null   int64
dtypes: int64(8), object(13)
memory usage: 164.2+ KB
None
          duration  credit_amount  installment_rate  residents_since  \
count  1000.000000    1000.000000       1000.000000      1000.000000
mean     20.903000    3271.258000          2.973000         2.845000
std      12.058814    2822.736876          1.118715         1.103718
min       4.000000     250.000000          1.000000         1.000000
25%      12.000000    1365.500000          2.000000         2.000000
50%      18.000000    2319.500000          3.000000         3.000000
75%      24.000000    3972.250000          4.000000         4.000000
max      72.000000   18424.000000          4.000000         4.000000

               age  existing_credits  maintainance_dependents  credit_risk
count  1000.000000       1000.000000              1000.000000  1000.000000
mean     35.546000          1.407000                 1.155000     1.300000
std      11.375469          0.577654                 0.362086     0.458487
min      19.000000          1.000000                 1.000000     1.000000
25%      27.000000          1.000000                 1.000000     1.000000
50%      33.000000          1.000000                 1.000000     1.000000
75%      42.000000          2.000000                 1.000000     2.000000
max      75.000000          4.000000                 2.000000     2.000000
cheking_status             0
duration                   0
credit_history             0
purpose                    0
credit_amount              0
savings                    0
employment                 0
installment_rate           0
personal_status_sex        0
other_debtors              0
residents_since            0
property                   0
age                        0
other_installment_plans    0
housing                    0
existing_credits           0
job                        0
maintainance_dependents    0
telephone                  0
foreign_worker             0
credit_risk                0
dtype: int64
1    700
2    300
Name: credit_risk, dtype: int64

In [18]:
for col in df.columns:
    print(f"\n{col}")
    print(df[col].unique())

cheking_status
['A11' 'A12' 'A14' 'A13']

duration
[ 6 48 12 42 24 36 30 15  9 10  7 60 18 45 11 27  8 54 20 14 33 21 16  4
 47 13 22 39 28  5 26 72 40]

credit_history
['A34' 'A32' 'A33' 'A30' 'A31']

purpose
['A43' 'A46' 'A42' 'A40' 'A41' 'A49' 'A44' 'A45' 'A410' 'A48']

credit_amount
[ 1169  5951  2096  7882  4870  9055  2835  6948  3059  5234  1295  4308
  1567  1199  1403  1282  2424  8072 12579  3430  2134  2647  2241  1804
  2069  1374   426   409  2415  6836  1913  4020  5866  1264  1474  4746
  6110  2100  1225   458  2333  1158  6204  6187  6143  1393  2299  1352
  7228  2073  5965  1262  3378  2225   783  6468  9566  1961  6229  1391
  1537  1953 14421  3181  5190  2171  1007  1819  2394  8133   730  1164
  5954  1977  1526  3965  4771  9436  3832  5943  1213  1568  1755  2315
  1412 12612  2249  1108   618  1409   797  3617  1318 15945  2012  2622
  2337  7057  1469  2323   932  1919  2445 11938  6458  6078  7721  1410
  1449   392  6260  7855  1680  3578  7174  2132  4281  2366  1835  3868
  1768   781  1924  2121   701   639  1860  3499  8487  6887  2708  1984
 10144  1240  8613   766  2728  1881   709  4795  3416  2462  2288  3566
   860   682  5371  1582  1346  5848  7758  6967  1288   339  3512  1898
  2872  1055  7308   909  2978  1131  1577  3972  1935   950   763  2064
  1414  3414  7485  2577   338  1963   571  9572  4455  1647  3777   884
  1360  5129  1175   674  3244  4591  3844  3915  2108  3031  1501  1382
   951  2760  4297   936  1168  5117   902  1495 10623  1424  6568  1413
  3074  3835  5293  1908  3342  3104  3913  3021  1364   625  1200   707
  4657  2613 10961  7865  1478  3149  4210  2507  2141   866  1544  1823
 14555  2767  1291  2522   915  1595  4605  1185  3447  1258   717  1204
  1925   433   666  2251  2150  4151  2030  7418  2684  2149  3812  1154
  1657  1603  5302  2748  1231   802  6304  1533  8978   999  2662  1402
 12169  3060 11998  2697  2404  4611  1901  3368  1574  1445  1520  3878
 10722  4788  7582  1092  1024  1076  9398  6419  4796  7629  9960  4675
  1287  2515  2745   672  3804  1344  1038 10127  1543  4811   727  1237
   276  5381  5511  3749   685  1494  2746   708  4351  3643  4249  1938
  2910  2659  1028  3398  5801  1525  4473  1068  6615  1864  7408 11590
  4110  3384  2101  1275  4169  1521  5743  3599  3213  4439  3949  1459
   882  3758  1743  1136  1236   959  3229  6199  1246  2331  4463   776
  2406  1239  3399  2247  1766  2473  1542  3850  3650  3446  3001  3079
  6070  2146 13756 14782  7685  2320   846 14318   362  2212 12976  1283
  1330  4272  2238  1126  7374  2326  1820   983  3249  1957 11760  2578
  2348  1223  1516  1473  1887  8648  2899  2039  2197  1053  3235   939
  1967  7253  2292  1597  1381  5842  2579  8471  2782  1042  3186  2028
   958  1591  2762  2779  2743  1149  1313  1190  3448 11328  1872  2058
  2136  1484   660  3394   609  1884  1620  2629   719  5096  1244  1842
  2576  1512 11054   518  2759  2670  4817  2679  3905  3386   343  4594
  3620  1721  3017   754  1950  2924  1659  7238  2764  4679  3092   448
   654  1238  1245  3114  2569  5152  1037  3573  1201  3622   960  1163
  1209  3077  3757  1418  3518  1934  8318   368  2122  2996  9034  1585
  1301  1323  3123  5493  1216  1207  1309  2360  6850  8588   759  4686
  2687   585  2255  1361  7127  1203   700  5507  3190  7119  3488  1113
  7966  1532  1503  2302   662  2273  2631  1311  3105  2319  3612  7763
  3049  1534  2032  6350  2864  1255  1333  2022  1552   626  8858   996
  1750  6999  1995  1331  2278  5003  3552  1928  2964  1546   683 12389
  4712  1553  1372  3979  6758  3234  5433   806  1082  2788  2930  1927
  2820   937  1056  3124  1388  2384  2133  2799  1289  1217  2246   385
  1965  1572  2718  1358   931  1442  4241  2775  3863  2329   918  1837
  3349  2828  4526  2671  2051  1300   741  3357  3632  1808 12204  9157
  3676  3441   640  3652  1530  3914  1858  2600  1979  2116  1437  4042
  3660  1444  1980  1355  1376 15653  1493  4370   750  1308  4623  1851
  1880  7980  4583  1386   947   684  7476  1922  2303  8086  2346  3973
   888 10222  4221  6361  1297   900  1050  1047  6314  3496  3609  4843
  4139  5742 10366  2080  2580  4530  5150  5595  1453  1538  2279  5103
  9857  6527  1347  2862  2753  3651   975  2896  4716  2284  1103   926
  1800  1905  1123  6331  1377  2503  2528  5324  6560  2969  1206  2118
   629  1198  2476  1138 14027  7596  1505  3148  6148  1337  1228   790
  2570   250  1316  1882  6416  6403  1987   760  2603  3380  3990 11560
  4380  6761  4280  2325  1048  3160  2483 14179  1797  2511  1274  5248
  3029   428   976   841  5771  1555  1285  1299  1271   691  5045  2124
  2214 12680  2463  1155  3108  2901  1655  2812  8065  3275  2223  1480
  1371  3535  3509  5711  3872  4933  1940   836  1941  2675  2751  6224
  5998  1188  6313  1221  2892  3062  2301  7511  1549  1795  7472  9271
   590   930  9283  1778   907   484  9629  3051  3931  7432  1338  1554
 15857  1345  1101  3016  2712   731  3780  1602  3966  4165  8335  6681
  2375 11816  5084  2327   886   601  2957  2611  5179  2993  1943  1559
  3422  3976  1249  2235  1471 10875   894  3343  3959  3577  5804  2169
  2439  2210  2221  2389  3331  7409   652  7678  1343   874  3590  1322
  3595  1422  6742  7814  9277  2181  1098  4057   795  2825 15672  6614
  7824  2442  1829  5800  8947  2606  1592  2186  4153  2625  3485 10477
  1278  1107  3763  3711  3594  3195  4454  4736  2991  2142  3161 18424
  2848 14896  2359  3345  1817 12749  1366  2002  6872   697  1049 10297
  1867  1747  1670  1224   522  1498   745  2063  6288  6842  3527   929
  1455  1845  8358  2859  3621  2145  4113 10974  1893  3656  4006  3069
  1740  2353  3556  2397   454  1715  2520  3568  7166  3939  1514  7393
  1193  7297  2831   753  2427  2538  8386  4844  2923  8229  1433  6289
  6579  3565  1569  1936  2390  1736  3857   804  4576]

savings
['A65' 'A61' 'A63' 'A64' 'A62']

employment
['A75' 'A73' 'A74' 'A71' 'A72']

installment_rate
[4 2 3 1]

personal_status_sex
['A93' 'A92' 'A91' 'A94']

other_debtors
['A101' 'A103' 'A102']

residents_since
[4 2 3 1]

property
['A121' 'A122' 'A124' 'A123']

age
[67 22 49 45 53 35 61 28 25 24 60 32 44 31 48 26 36 39 42 34 63 27 30 57
 33 37 58 23 29 52 50 46 51 41 40 66 47 56 54 20 21 38 70 65 74 68 43 55
 64 75 19 62 59]

other_installment_plans
['A143' 'A141' 'A142']

housing
['A152' 'A153' 'A151']

existing_credits
[2 1 3 4]

job
['A173' 'A172' 'A174' 'A171']

maintainance_dependents
[1 2]

telephone
['A192' 'A191']

foreign_worker
['A201' 'A202']

credit_risk
[1 2]

In [19]:
#distribution of features categories
for col in df.columns:
    print(f"\n{col}")
    print(df[col].value_counts())

cheking_status
A14    394
A11    274
A12    269
A13     63
Name: cheking_status, dtype: int64

duration
24    184
12    179
18    113
36     83
6      75
15     64
9      49
48     48
30     40
21     30
10     28
60     13
27     13
42     11
11      9
20      8
8       7
4       6
45      5
7       5
39      5
14      4
13      4
33      3
28      3
54      2
16      2
22      2
47      1
5       1
26      1
72      1
40      1
Name: duration, dtype: int64

credit_history
A32    530
A34    293
A33     88
A31     49
A30     40
Name: credit_history, dtype: int64

purpose
A43     280
A40     234
A42     181
A41     103
A49      97
A46      50
A45      22
A44      12
A410     12
A48       9
Name: purpose, dtype: int64

credit_amount
1478    3
1262    3
1258    3
1275    3
1393    3
       ..
1459    1
882     1
3758    1
1136    1
4576    1
Name: credit_amount, Length: 921, dtype: int64

savings
A61    603
A65    183
A62    103
A63     63
A64     48
Name: savings, dtype: int64

employment
A73    339
A75    253
A74    174
A72    172
A71     62
Name: employment, dtype: int64

installment_rate
4    476
2    231
3    157
1    136
Name: installment_rate, dtype: int64

personal_status_sex
A93    548
A92    310
A94     92
A91     50
Name: personal_status_sex, dtype: int64

other_debtors
A101    907
A103     52
A102     41
Name: other_debtors, dtype: int64

residents_since
4    413
2    308
3    149
1    130
Name: residents_since, dtype: int64

property
A123    332
A121    282
A122    232
A124    154
Name: property, dtype: int64

age
27    51
26    50
23    48
24    44
28    43
25    41
30    40
35    40
36    39
31    38
29    37
32    34
33    33
34    32
37    29
22    27
40    25
38    24
42    22
39    21
46    18
43    17
47    17
44    17
41    17
45    15
20    14
21    14
49    14
50    12
48    12
54    10
57     9
52     9
51     8
55     8
63     8
61     7
53     7
60     6
65     5
58     5
64     5
66     5
74     4
67     3
68     3
56     3
59     3
75     2
19     2
62     2
70     1
Name: age, dtype: int64

other_installment_plans
A143    814
A141    139
A142     47
Name: other_installment_plans, dtype: int64

housing
A152    713
A151    179
A153    108
Name: housing, dtype: int64

existing_credits
1    633
2    333
3     28
4      6
Name: existing_credits, dtype: int64

job
A173    630
A172    200
A174    148
A171     22
Name: job, dtype: int64

maintainance_dependents
1    845
2    155
Name: maintainance_dependents, dtype: int64

telephone
A191    596
A192    404
Name: telephone, dtype: int64

foreign_worker
A201    963
A202     37
Name: foreign_worker, dtype: int64

credit_risk
1    700
2    300
Name: credit_risk, dtype: int64

# Classifying columns into numerical and categorical